### PR TITLE
allow beforeCreate to return a promise

### PR DESCRIPTION
**Pull request by mpycio**
In my scenario I need to make a get request to a remote api to fetch some extra data, this change allows user to return a Promise from beforeCreate callback in case some async work is needed. This may be my very specific case but maybe it can be used by others. Only difference is that beforeCreate must now return a value instead of just modifying data in newUser parameter.

### CODE REVIEW

**Comment by jmls** [comment]
thanks for the PR - I am slightly confused about your comment 

> Only difference is that beforeCreate must now return a value instead of just modifying data in newUser parameter.

does this mean that it is not backwards-compatible ? If so, that would break all existing apps that use this lib and we won't be able to merge it in. 

We really would like to include this functionality, but it does need to not break any existing app out there already ;)

thanks again !

**Comment by jmls** [comment]
thanks!

**Comment by mpycio** [comment]
That was quick, I was about to reply.

Yes it was breaking backwards compatibility but fix was rather easy to implement, I tested it in old scenario and with return value and promise.

I would like to add some tests to this project but before I do just wanted to check it's something you would merge and if so if mocha/chai/sinon are ok to be added as dev dependencies.

**Comment by jmls** [comment]
I would be extremely grateful if you would take the time to add some tests ! please ;) Thanks for the offer.

**Pull request merged**
